##########################################################################
# Title:         Saltbox: Plex | Default Variables                       #
# Author(s):     desimaniac, salty                                       #
# URL:           https://github.com/saltyorg/Saltbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

plex_instances: ["plex"]

################################
# Settings
################################

plex_role_open_main_ports: false
plex_role_open_local_ports: false
plex_role_plugin_webtools: false
plex_role_plugin_sub_zero: false
plex_role_insecure: false
plex_role_lan_ip: ""

################################
# Proxy
################################

# For instances this works the same as usual plex2_auth_token_proxy for an instance named plex2.
plex_role_auth_token_proxy: ""

plex_proxy_dict:
  http_proxy: "{{ plex_role_proxy_lookup if (plex_role_proxy_lookup | length > 0) else '' }}"
  https_proxy: "{{ plex_role_proxy_lookup if (plex_role_proxy_lookup | length > 0) else '' }}"

# Do not edit or override using the inventory
plex_role_proxy_lookup: "{{ lookup('role_var', '_auth_token_proxy', role='plex') }}"
plex_role_network_modes: []

################################
# Paths
################################

plex_role_paths_folder: "{{ plex_name }}"
plex_role_paths_location: "{{ server_appdata_path }}/{{ plex_role_paths_folder }}"
plex_role_paths_transcodes_location: "{{ transcodes_path }}/{{ plex_role_paths_folder }}"
plex_role_paths_folders_list:
  - "{{ plex_role_paths_location }}"
  - "{{ plex_role_paths_location }}/Library"
  - "{{ plex_role_paths_location }}/Library/Application Support"
  - "{{ plex_role_paths_location }}/Library/Application Support/Plex Media Server"
  - "{{ plex_role_paths_location }}/Library/Application Support/Plex Media Server/Plug-ins"
  - "{{ plex_role_paths_location }}/Library/Logs"
  - "{{ plex_role_paths_location }}/Library/Logs/Plex Media Server"
  - "{{ plex_role_paths_transcodes_location }}"
plex_role_paths_application_support_location: "{{ plex_role_paths_location }}/Library/Application Support/Plex Media Server"
plex_role_paths_config_location: "{{ plex_role_paths_application_support_location }}/Preferences.xml"
plex_role_paths_log_location: "{{ plex_role_paths_application_support_location }}/Logs"
plex_role_paths_plugins_location: "{{ plex_role_paths_application_support_location }}/Plug-ins"
plex_role_paths_plugin_support_location: "{{ plex_role_paths_application_support_location }}/Plug-in Support"
plex_role_paths_db_location: "{{ plex_role_paths_plugin_support_location }}/Databases/com.plexapp.plugins.library.db"
plex_role_paths_db_blobs_location: "{{ plex_role_paths_plugin_support_location }}/Databases/com.plexapp.plugins.library.blobs.db"

################################
# Web
################################

plex_role_web_subdomain: "{{ plex_name }}"
plex_role_web_domain: "{{ user.domain }}"
plex_role_web_port: "32400"
plex_role_web_scheme: "https"
plex_role_web_http_port: "32400"
plex_role_web_http_scheme: "http"
plex_role_web_url: "{{ 'https://' + (lookup('vars', plex_name + '_web_subdomain', default=plex_role_web_subdomain) + '.' + lookup('vars', plex_name + '_web_domain', default=plex_role_web_domain)
                    if (lookup('vars', plex_name + '_web_subdomain', default=plex_role_web_subdomain) | length > 0)
                    else lookup('vars', plex_name + '_web_domain', default=plex_role_web_domain)) }}"
plex_role_webtools_web_subdomain: "{{ plex_name }}-webtools"
plex_role_webtools_web_domain: "{{ plex_role_web_domain }}"
plex_role_webtools_web_port: "33400"
plex_role_webtools_host: "{{ lookup('vars', plex_name + '_webtools_web_subdomain', default=plex_role_webtools_web_subdomain)
                             + '.' + lookup('vars', plex_name + '_webtools_web_domain', default=plex_role_webtools_web_domain) }}"
plex_role_web_insecure_url: "{{ 'http://' + (lookup('vars', plex_name + '_web_subdomain', default=plex_role_web_subdomain) + '.' + lookup('vars', plex_name + '_web_domain', default=plex_role_web_domain)
                             if (lookup('vars', plex_name + '_web_subdomain', default=plex_role_web_subdomain) | length > 0)
                             else lookup('vars', plex_name + '_web_domain', default=plex_role_web_domain)) }}"

################################
# DNS
################################

plex_role_dns_record: "{{ lookup('vars', plex_name + '_web_subdomain', default=plex_role_web_subdomain) }}"
plex_role_dns_zone: "{{ lookup('vars', plex_name + '_web_domain', default=plex_role_web_domain) }}"
plex_role_dns_proxy: "{{ lookup('vars', plex_name + '_web_proxy', default=(dns.proxied | bool)) }}"
plex_role_webtools_dns_record: "{{ lookup('vars', plex_name + '_webtools_web_subdomain', default=plex_role_webtools_web_subdomain) }}"
plex_role_webtools_dns_zone: "{{ lookup('vars', plex_name + '_webtools_web_domain', default=plex_role_webtools_web_domain) }}"
plex_role_webtools_dns_proxy: "{{ lookup('vars', plex_name + '_webtools_web_proxy', default=(dns.proxied | bool)) }}"

################################
# Traefik
################################

plex_role_traefik_sso_middleware: ""
plex_role_traefik_middleware_default: "{{ traefik_default_middleware
                                     + (',themepark-' + lookup('vars', plex_name + '_name', default=plex_name)
                                       if (plex_themepark_enabled and global_themepark_plugin_enabled)
                                       else '') }}"
plex_role_traefik_middleware_custom: ""
plex_role_traefik_certresolver: "{{ traefik_default_certresolver }}"
plex_role_traefik_enabled: true
plex_role_traefik_api_enabled: false
plex_role_traefik_api_endpoint: ""
plex_role_traefik_error_pages_enabled: false
plex_role_traefik_gzip_enabled: false

plex_role_traefik_middleware_http: "{{ 'globalHeaders@file'
                               if lookup('vars', plex_name + '_insecure', default=plex_role_insecure)
                               else traefik_default_middleware_default_http }}"
plex_role_web_serverstransport: "skipverify@file"

plex_role_webtools_traefik_sso_middleware: ""
plex_role_webtools_traefik_middleware_default: "{{ traefik_default_middleware
                                                   + (',' + lookup('vars', plex_name + '_webtools_traefik_sso_middleware', default=plex_role_webtools_traefik_sso_middleware)
                                                     if (lookup('vars', plex_name + '_webtools_traefik_sso_middleware', default=plex_role_webtools_traefik_sso_middleware) | length > 0)
                                                     else '') }}"
plex_role_webtools_traefik_middleware_custom: ""
plex_role_webtools_traefik_middleware: "{{ plex_role_webtools_traefik_middleware_default
                                           + (',' + plex_role_webtools_traefik_middleware_custom
                                             if (not plex_role_webtools_traefik_middleware_custom.startswith(',') and plex_role_webtools_traefik_middleware_custom | length > 0)
                                             else plex_role_webtools_traefik_middleware_custom) }}"
plex_role_webtools_traefik_certresolver: "{{ traefik_default_certresolver }}"
plex_role_webtools_traefik_router: "{{ lookup('vars', plex_name + '_webtools_web_subdomain', default=plex_role_webtools_web_subdomain) }}"

################################
# THEME
################################

# Options can be found at https://github.com/themepark-dev/theme.park
plex_role_themepark_enabled: false
plex_role_themepark_app: "plex"
plex_role_themepark_theme: "{{ global_themepark_theme }}"
plex_role_themepark_domain: "{{ global_themepark_domain }}"
plex_role_themepark_addons: []

################################
# Docker
################################

# Container
plex_role_docker_container: "{{ plex_name }}"

# Image
plex_role_docker_image_pull: true
plex_role_docker_image_repo: "plexinc/pms-docker"
plex_role_docker_image_tag: "latest"
plex_role_docker_image: "{{ lookup('vars', plex_name + '_docker_image_repo', default=plex_role_docker_image_repo)
                            + ':' + lookup('vars', plex_name + '_docker_image_tag', default=plex_role_docker_image_tag) }}"

# Ports
plex_role_docker_ports_32400: "{{ port_lookup_32400.meta.port
                               if (port_lookup_32400.meta.port is defined) and (port_lookup_32400.meta.port | trim | length > 0)
                               else '32400' }}"

plex_role_docker_ports_defaults: []
plex_role_docker_ports_local:
  - "1900:1900/udp"
  - "5353:5353/udp"
  - "8324:8324"
  - "32410:32410/udp"
  - "32412:32412/udp"
  - "32414:32414/udp"
  - "32469:32469"
plex_role_docker_ports_ui:
  - "{{ plex_role_docker_ports_32400 }}:{{ lookup('vars', plex_name + '_web_port', default=plex_role_web_port) }}"
plex_role_docker_ports_custom: []
plex_role_docker_ports: "{{ lookup('vars', plex_name + '_docker_ports_defaults', default=plex_role_docker_ports_defaults)
                            + lookup('vars', plex_name + '_docker_ports_custom', default=plex_role_docker_ports_custom)
                            + (plex_role_docker_ports_local
                              if (lookup('vars', plex_name + '_open_local_ports', default=plex_role_open_local_ports))
                              else [])
                            + (plex_role_docker_ports_ui
                              if lookup('vars', plex_name + '_open_main_ports', default=plex_role_open_main_ports)
                              else []) }}"

# Envs
plex_role_docker_envs_advertise_ip_url: "{{ lookup('vars', plex_name + '_web_url', default=plex_role_web_url) + ':443,' + lookup('vars', plex_name + '_web_insecure_url', default=plex_role_web_insecure_url) + ':80'
                                         if lookup('vars', plex_name + '_insecure', default=plex_role_insecure)
                                         else lookup('vars', plex_name + '_web_url', default=plex_role_web_url) + ':443' }}"
plex_role_docker_envs_advertise_ip: "{{ 'http://' + lookup('vars', plex_name + '_lan_ip', default=plex_role_lan_ip) + ':32400,' + lookup('vars', plex_name + '_docker_envs_advertise_ip_url', default=plex_role_docker_envs_advertise_ip_url)
                                     if (lookup('vars', plex_name + '_lan_ip', default=plex_role_lan_ip) | length > 0) and lookup('vars', plex_name + '_open_main_ports', default=plex_role_open_main_ports)
                                     else lookup('vars', plex_name + '_docker_envs_advertise_ip_url', default=plex_role_docker_envs_advertise_ip_url) }}"
plex_role_docker_envs_default:
  PLEX_UID: "{{ uid }}"
  PLEX_GID: "{{ gid }}"
  PLEX_CLAIM: "{{ (plex_claim_code) | default(omit) }}"
  CHANGE_CONFIG_DIR_OWNERSHIP: "false"
  TZ: "{{ tz }}"
  ADVERTISE_IP: "{{ plex_role_docker_envs_advertise_ip }}"
plex_role_docker_envs_custom: {}
plex_role_docker_envs: "{{ lookup('vars', plex_name + '_docker_envs_default', default=plex_role_docker_envs_default)
                           | combine(lookup('vars', plex_name + '_docker_envs_custom', default=plex_role_docker_envs_custom)) }}"

# Commands
plex_role_docker_commands_default: []
plex_role_docker_commands_custom: []
plex_role_docker_commands: "{{ lookup('vars', plex_name + '_docker_commands_default', default=plex_role_docker_commands_default)
                               + lookup('vars', plex_name + '_docker_commands_custom', default=plex_role_docker_commands_custom) }}"

# Volumes
plex_role_docker_volumes_default:
  - "{{ plex_role_paths_location }}:/config"
  - "{{ server_appdata_path }}/scripts:/scripts"
  - "/dev/shm:/dev/shm"
  - "{{ plex_role_paths_transcodes_location }}:/transcode"
plex_role_docker_volumes_legacy:
  - "/mnt/unionfs/Media:/data"
plex_role_docker_volumes_custom: []
plex_role_docker_volumes: "{{ lookup('vars', plex_name + '_docker_volumes_default', default=plex_role_docker_volumes_default)
                              + lookup('vars', plex_name + '_docker_volumes_custom', default=plex_role_docker_volumes_custom)
                              + (lookup('vars', plex_name + '_docker_volumes_legacy', default=plex_role_docker_volumes_legacy)
                                if docker_legacy_volume
                                else []) }}"

# Mounts
plex_role_docker_mounts_default:
  - target: /tmp
    type: tmpfs
plex_role_docker_mounts_custom: []
plex_role_docker_mounts: "{{ lookup('vars', plex_name + '_docker_mounts_default', default=plex_role_docker_mounts_default)
                             + lookup('vars', plex_name + '_docker_mounts_custom', default=plex_role_docker_mounts_custom) }}"

# Devices
plex_role_docker_devices_default: []
plex_role_docker_devices_custom: []
plex_role_docker_devices: "{{ lookup('vars', plex_name + '_docker_devices_default', default=plex_role_docker_devices_default)
                              + lookup('vars', plex_name + '_docker_devices_custom', default=plex_role_docker_devices_custom) }}"

# Hosts
plex_role_docker_hosts_default:
  metric.plex.tv: "{{ ip_address_localhost }}"
  metrics.plex.tv: "{{ ip_address_localhost }}"
  analytics.plex.tv: "{{ ip_address_localhost }}"
plex_role_docker_hosts_custom: {}
plex_role_docker_hosts: "{{ docker_hosts_common
                            | combine(lookup('vars', plex_name + '_docker_hosts_default', default=plex_role_docker_hosts_default))
                            | combine(lookup('vars', plex_name + '_docker_hosts_custom', default=plex_role_docker_hosts_custom)) }}"

# Labels
plex_role_docker_labels_default:
  - '{ "traefik.http.routers.{{ plex_role_webtools_traefik_router }}-http.entrypoints": "web" }'
  - '{ "traefik.http.routers.{{ plex_role_webtools_traefik_router }}-http.service": "{{ lookup("vars", plex_name + "_webtools_web_subdomain", default=plex_role_webtools_web_subdomain) }}" }'
  - '{ "traefik.http.routers.{{ plex_role_webtools_traefik_router }}-http.rule": "Host(`{{ plex_role_webtools_host }}`)" }'
  - '{ "traefik.http.routers.{{ plex_role_webtools_traefik_router }}-http.middlewares": "{{ traefik_default_middleware_http }}" }'
  - '{ "traefik.http.routers.{{ plex_role_webtools_traefik_router }}-http.priority": "20" }'
  - '{ "traefik.http.routers.{{ plex_role_webtools_traefik_router }}.entrypoints": "websecure" }'
  - '{ "traefik.http.routers.{{ plex_role_webtools_traefik_router }}.service": "{{ lookup("vars", plex_name + "_webtools_web_subdomain", default=plex_role_webtools_web_subdomain) }}" }'
  - '{ "traefik.http.routers.{{ plex_role_webtools_traefik_router }}.rule": "Host(`{{ plex_role_webtools_host }}`)" }'
  - '{ "traefik.http.routers.{{ plex_role_webtools_traefik_router }}.tls.options": "securetls@file" }'
  - '{ "traefik.http.routers.{{ plex_role_webtools_traefik_router }}.tls.certresolver": "{{ plex_role_webtools_traefik_certresolver }}" }'
  - '{ "traefik.http.routers.{{ plex_role_webtools_traefik_router }}.middlewares": "{{ plex_role_webtools_traefik_middleware }}" }'
  - '{ "traefik.http.routers.{{ plex_role_webtools_traefik_router }}.priority": "20" }'
  - '{ "traefik.http.services.{{ plex_role_webtools_traefik_router }}.loadbalancer.server.port": "{{ plex_role_webtools_web_port }}" }'
plex_role_docker_labels_custom: {}
plex_role_docker_labels: "{{ docker_labels_common
                             | combine((lookup('vars', plex_name + '_docker_labels_default', default=plex_role_docker_labels_default)
                                       if lookup('vars', plex_name + '_plugin_webtools', default=plex_role_plugin_webtools)
                                       else {}),
                                       (traefik_themepark_labels
                                       if (plex_themepark_enabled and global_themepark_plugin_enabled)
                                       else {}),
                                       lookup('vars', plex_name + '_docker_labels_custom', default=plex_role_docker_labels_custom)) }}"

# Hostname
plex_role_docker_hostname: "{{ plex_name }}"

# Networks
plex_role_docker_networks_alias: "{{ plex_name }}"
plex_role_docker_networks_default: []
plex_role_docker_networks_custom: []
plex_role_docker_networks: "{{ docker_networks_common
                               + lookup('vars', plex_name + '_docker_networks_default', default=plex_role_docker_networks_default)
                               + lookup('vars', plex_name + '_docker_networks_custom', default=plex_role_docker_networks_custom) }}"

# Capabilities
plex_role_docker_capabilities_default: []
plex_role_docker_capabilities_custom: []
plex_role_docker_capabilities: "{{ lookup('vars', plex_name + '_docker_capabilities_default', default=plex_role_docker_capabilities_default)
                                   + lookup('vars', plex_name + '_docker_capabilities_custom', default=plex_role_docker_capabilities_custom) }}"

# Security Opts
plex_role_docker_security_opts_default: []
plex_role_docker_security_opts_custom: []
plex_role_docker_security_opts: "{{ lookup('vars', plex_name + '_docker_security_opts_default', default=plex_role_docker_security_opts_default)
                                    + lookup('vars', plex_name + '_docker_security_opts_custom', default=plex_role_docker_security_opts_custom) }}"

# Restart Policy
plex_role_docker_restart_policy: unless-stopped

# State
plex_role_docker_state: started
